### ISSUE TITLE
根据Url获取Bitmap , 得到Bitmap后设置给ImageView 在列表中报"java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@692613a" 

### ISSUE THREAD

**Issue by bobSir** [glassLake/FrescoUtlis#1]

**Comment by bobSir** [comment]
Up 有没有什么方法解决

**Comment by hss01248** [comment]
用fresco的时候,imageview要换成fresco自己的simpledraweeView,尤其是listview这种复用情况下
这个项目不维护了,最新的在这里:
https://github.com/hss01248/ImageLoader
基于glide和fresco的api封装,以及优化,以及大图加载的实现.
实现了不同的第三方库切换时,完全不需要改api,只要改改imageview就好了.
女程序猿?

**Comment by bobSir** [comment]
项目采用图片加载框架是Fresco，现在要解决的是利用Fresco下载图片 得到Bitmap以后设置给ImageView ,

**Comment by hss01248** [comment]
既然用fresco,那为什么非得用原生的imageview? @bobSir

**Comment by bobSir** [comment]
我要拿到Drawable 对其做动画

**Comment by hss01248** [comment]
直接对整个view做动画不就行了? 属性动画怎么搞都行啊,为什么要拿到Drawable ?难道你想imageview内部末一块区域做动画?
列表中的bitmap对象随着滑动是会被回收的,没有深入源码去看有没有不回收的设置.

**Comment by bobSir** [comment]
嗯 3q  问题已经解决了


duanfasir@163.com
 
发件人： 水牛
发送时间： 2017-04-21 13:41
收件人： glassLake/FrescoUtlis
抄送： Bob; Mention
主题： Re: [glassLake/FrescoUtlis] 根据Url获取Bitmap , 得到Bitmap后设置给ImageView 在列表中报"java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@692613a" (#1)
既然用fresco,那为什么非得用原生的imageview? @bobSir
